POST  https://fullstackopen-puhelinluettelo-backend-h33y.onrender.com/api/persons
Content-Type: application/json

{
    "name":"RP", 
    "number":"+358 41 726251"
}

# GET http://localhost:3001/api/persons
